# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MjUxNDhkOTEwZjlhYmRmNWNhYjkwYjI2Njg0NTk1N2RhOTQ3MmYzMWZiMzM4MzljYjQ4MjQ2Yzg2NzgwNjdmMmZiMWU1NmY0ZWZmOWE2ZmNmNjIwMzEyY2UxYTgwNGRkNzE0NThhNzNlYjJhNDNiZDRjMDk0NmVjNWNjN2ZjYmY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
